//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PsebPrimaryMiddle.ingovepunjabschool {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Threading;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="service_pseb_5th_and_8thSoap", Namespace="https://tempuri.org/")]
    public partial class service_pseb_5th_and_8th : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get5thAnd8ththClassAllStudentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback get5thAnd8thClassStudentDetails_ByStudentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback get5thAnd8ththClassStudentDetails_ByUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSchoolDetailsByUdiseCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service_pseb_5th_and_8th() {
            this.Url = global::PsebPrimaryMiddle.Properties.Settings.Default.PsebPrimaryMiddle_ingovepunjabschool_service_pseb_5th_and_8th;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get5thAnd8ththClassAllStudentsCompletedEventHandler get5thAnd8ththClassAllStudentsCompleted;
        
        /// <remarks/>
        public event get5thAnd8thClassStudentDetails_ByStudentsCompletedEventHandler get5thAnd8thClassStudentDetails_ByStudentsCompleted;
        
        /// <remarks/>
        public event get5thAnd8ththClassStudentDetails_ByUIDCompletedEventHandler get5thAnd8ththClassStudentDetails_ByUIDCompleted;
        
        /// <remarks/>
        public event getSchoolDetailsByUdiseCodeCompletedEventHandler getSchoolDetailsByUdiseCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get5thAnd8ththClassAllStudents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get5thAnd8ththClassAllStudents(string paramerter) {
            
            object[] results = this.Invoke("get5thAnd8ththClassAllStudents", new object[] {
                        paramerter});
            Thread.Sleep(10000);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get5thAnd8ththClassAllStudentsAsync(string paramerter) {
            this.get5thAnd8ththClassAllStudentsAsync(paramerter, null);
        }
        
        /// <remarks/>
        public void get5thAnd8ththClassAllStudentsAsync(string paramerter, object userState) {
            if ((this.get5thAnd8ththClassAllStudentsOperationCompleted == null)) {
                this.get5thAnd8ththClassAllStudentsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget5thAnd8ththClassAllStudentsOperationCompleted);
            }
            this.InvokeAsync("get5thAnd8ththClassAllStudents", new object[] {
                        paramerter}, this.get5thAnd8ththClassAllStudentsOperationCompleted, userState);
        }
        
        private void Onget5thAnd8ththClassAllStudentsOperationCompleted(object arg) {
            if ((this.get5thAnd8ththClassAllStudentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get5thAnd8ththClassAllStudentsCompleted(this, new get5thAnd8ththClassAllStudentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get5thAnd8thClassStudentDetails_ByStudents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get5thAnd8thClassStudentDetails_ByStudents(string paramerter) {
            object[] results = this.Invoke("get5thAnd8thClassStudentDetails_ByStudents", new object[] {
                        paramerter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get5thAnd8thClassStudentDetails_ByStudentsAsync(string paramerter) {
            this.get5thAnd8thClassStudentDetails_ByStudentsAsync(paramerter, null);
        }
        
        /// <remarks/>
        public void get5thAnd8thClassStudentDetails_ByStudentsAsync(string paramerter, object userState) {
            if ((this.get5thAnd8thClassStudentDetails_ByStudentsOperationCompleted == null)) {
                this.get5thAnd8thClassStudentDetails_ByStudentsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget5thAnd8thClassStudentDetails_ByStudentsOperationCompleted);
            }
            this.InvokeAsync("get5thAnd8thClassStudentDetails_ByStudents", new object[] {
                        paramerter}, this.get5thAnd8thClassStudentDetails_ByStudentsOperationCompleted, userState);
        }
        
        private void Onget5thAnd8thClassStudentDetails_ByStudentsOperationCompleted(object arg) {
            if ((this.get5thAnd8thClassStudentDetails_ByStudentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get5thAnd8thClassStudentDetails_ByStudentsCompleted(this, new get5thAnd8thClassStudentDetails_ByStudentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get5thAnd8ththClassStudentDetails_ByUID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get5thAnd8ththClassStudentDetails_ByUID(string paramerter) {
            object[] results = this.Invoke("get5thAnd8ththClassStudentDetails_ByUID", new object[] {
                        paramerter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get5thAnd8ththClassStudentDetails_ByUIDAsync(string paramerter) {
            this.get5thAnd8ththClassStudentDetails_ByUIDAsync(paramerter, null);
        }
        
        /// <remarks/>
        public void get5thAnd8ththClassStudentDetails_ByUIDAsync(string paramerter, object userState) {
            if ((this.get5thAnd8ththClassStudentDetails_ByUIDOperationCompleted == null)) {
                this.get5thAnd8ththClassStudentDetails_ByUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget5thAnd8ththClassStudentDetails_ByUIDOperationCompleted);
            }
            this.InvokeAsync("get5thAnd8ththClassStudentDetails_ByUID", new object[] {
                        paramerter}, this.get5thAnd8ththClassStudentDetails_ByUIDOperationCompleted, userState);
        }
        
        private void Onget5thAnd8ththClassStudentDetails_ByUIDOperationCompleted(object arg) {
            if ((this.get5thAnd8ththClassStudentDetails_ByUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get5thAnd8ththClassStudentDetails_ByUIDCompleted(this, new get5thAnd8ththClassStudentDetails_ByUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/getSchoolDetailsByUdiseCode", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSchoolDetailsByUdiseCode(string paramerter) {
            object[] results = this.Invoke("getSchoolDetailsByUdiseCode", new object[] {
                        paramerter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSchoolDetailsByUdiseCodeAsync(string paramerter) {
            this.getSchoolDetailsByUdiseCodeAsync(paramerter, null);
        }
        
        /// <remarks/>
        public void getSchoolDetailsByUdiseCodeAsync(string paramerter, object userState) {
            if ((this.getSchoolDetailsByUdiseCodeOperationCompleted == null)) {
                this.getSchoolDetailsByUdiseCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSchoolDetailsByUdiseCodeOperationCompleted);
            }
            this.InvokeAsync("getSchoolDetailsByUdiseCode", new object[] {
                        paramerter}, this.getSchoolDetailsByUdiseCodeOperationCompleted, userState);
        }
        
        private void OngetSchoolDetailsByUdiseCodeOperationCompleted(object arg) {
            if ((this.getSchoolDetailsByUdiseCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSchoolDetailsByUdiseCodeCompleted(this, new getSchoolDetailsByUdiseCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get5thAnd8ththClassAllStudentsCompletedEventHandler(object sender, get5thAnd8ththClassAllStudentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get5thAnd8ththClassAllStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get5thAnd8ththClassAllStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get5thAnd8thClassStudentDetails_ByStudentsCompletedEventHandler(object sender, get5thAnd8thClassStudentDetails_ByStudentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get5thAnd8thClassStudentDetails_ByStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get5thAnd8thClassStudentDetails_ByStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get5thAnd8ththClassStudentDetails_ByUIDCompletedEventHandler(object sender, get5thAnd8ththClassStudentDetails_ByUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get5thAnd8ththClassStudentDetails_ByUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get5thAnd8ththClassStudentDetails_ByUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getSchoolDetailsByUdiseCodeCompletedEventHandler(object sender, getSchoolDetailsByUdiseCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSchoolDetailsByUdiseCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSchoolDetailsByUdiseCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591